<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8"/>
        <PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\OpenTelemetry\OpenTelemetry.Shared\OpenTelemetry.Shared.csproj" />
      <ProjectReference Include="..\Grpc.Server.Shared\Grpc.Server.Shared.csproj" />
    </ItemGroup>

</Project>
