server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  pipeline_stages:
  - docker: {}
  - cri: {}
  - json:
      expressions:
        trace_id: traceId
        time: timestamp
        level: level
        need_alert: needAlert
        alert_event: alertEvent
        message: message
        logger: logger
  - template:
      source: trace_id
      template: '{{if .Value }} {{- .Value -}} {{else}} {{- "-" -}} {{end}}'
  - template:
      source: timestamp
      format: RFC3339
  - template:
      source: need_alert
      template: '{{if .Value }} {{- .Value -}} {{else}} {{- "-" -}} {{end}}'
  - template:
      source: alert_event
      template: '{{if .Value }} {{- .Value -}} {{else}} {{- "-" -}} {{end}}'
  - template:
      source: output
      template: '{{ ToUpper .level }} | AlertEvent: {{ .alert_event }} | TraceId: {{ .trace_id }} | {{ .message }} | {{ .logger }}'
  # - output:
  #     source: output
  - regex:
      expression: 'level": "(?P<level>[a-zA-z]{4,6})"'
  - labels:
      level:
      need_alert:
      alert_event:

